export const SUCCESS_HTTP_CODE = 200;
export const ERROR_IN_SERVER_HTTP_CODE = 500;
export const ERROR_NOT_FOUND_HTTP_CODE = 404;
export const ERROR_NOT_ACCESS_HTTP_CODE = 403;
export const ERROR_CONFLICT_HTTP_CODE = 409;
export const BAD_REQUEST_HTTP_CODE = 400;
